### ISSUE TITLE
Slider lose focus

### ISSUE THREAD

**Issue by MarcHbb** [Sharcoux/slider#15]
Hi ! 
When drag the slider and my finger is dragging from outside the slider bar, it's not working :/

**Comment by Sharcoux** [comment]
Hi
I'm not sure to understand what you mean. Could you maybe show a gif that would explain better?

**Comment by justsee** [comment]
If you embed your slider in a ScrollView with enough content to scroll, you should immediately see the issue.

After sliding the thumb of the slider, as soon as a portion of your finger goes out of bounds it triggers horizontal scrolling and the slider loses focus.

**Comment by Sharcoux** [comment]
I tried something, but it seems that we are caught in this bug: https://github.com/facebook/react-native/issues/5696
I'm affraid that there is not much I can do on my side. You will have to set scrollEnabled={false} while the silder is being used. You can use `onSlidingStart` and `onSlidingComplete` to handle that.

@MarcHbb @justsee would this solve your issue?

**Comment by Sharcoux** [comment]
I won't fix this internally due to [this bug](facebook/react-native#5696), and the solution is to make use of `scrollEnable` in conjunction with `onSlidingXXX` events. Feel free to reopen if needed.

**Comment by Sharcoux** [comment]
The problem lies in react-native, and this slider is a pure react-native implementation while callstack/ract-native-slider uses native implementations. It has other drawbacks, though. I guess that, depending on your needs, you can use either slider. Anyway, if you keep this one, you'll have to accept the "rules" imposed by the stack. And right now, the rule is to use "scrollEnable" just as mentioned in the earlier post and in the linked issues.

If someone has a better solution, feel free to suggest it.
