### ISSUE TITLE
[Android only] Value jumping to zero if user tries to slide up to the max value

### ISSUE THREAD

**Issue by moyolvera** [Sharcoux/slider#18]
I don't know if its a missconfiguration or if i'm doing something wrong. But on android if the user slides the thumb all the way to the maximum this goes back to the beginning.

`           <Slider
                  style={styles.slider}
                  thumbTintColor={APP_COLORS.GRAY2_LIGHT}
                  minimumValue={0}
                  maximumValue={20}
                  value={10}
                  step={1}
                  trackStyle={styles.trackStyle}
                  minimumTrackTintColor={APP_COLORS.PRIMARY}
                  maximumTrackTintColor={APP_COLORS.DARK}
            />
`

**Comment by Sharcoux** [comment]
I'll check that. Thanks for report.

Did you try on web and iOS? Is it truly Android only or is it just because you tested only there?

**Comment by moyolvera** [comment]
I didn’t tried on web, i tried iOS simulator, android device and android simulator, and it's only happening on android

**Comment by Sharcoux** [comment]
On web it's working as expected. It seems more like a bug with Android implementation of React Native... I'll need to investigate more.

Just to be sure that the behavior is the same: check [this snack](https://snack.expo.io/@sharcoux/slider)

Here, you will see that, as long as you are touching the track, the behavior is correct, but as soon as your finger goes below or above it, the touch event gets located relative to the parent component, meaning that 0 is now the left border of the device.

I checked on React-Native and the issue is coming from them actually. Check [this snack](https://snack.expo.io/@sharcoux/anroid-responder-event). You can check [This Issue](https://github.com/facebook/react-native/issues/31843) I've just created. But you can see that it has been reported [here](https://github.com/facebook/react-native/issues/27143) and [here](https://github.com/facebook/react-native/issues/15506) and [here](https://github.com/facebook/react-native/issues/3050).

Please, if you can, could you check on you Android device if you can replicate the issue with versions 64.2 of React-Native and version 62.2?

**Comment by Sharcoux** [comment]
Ah, and please add a thumb up on [this issue](https://github.com/facebook/react-native/issues/31843) as it might increase the chances of it being considered.

**Comment by moyolvera** [comment]
Wow, thanks for all the info. I'll take a look on those versions you mentioned above. For now I'm going to go ahead and use the community/slider so I can continue working but I'll keep an eye on those issues. Thanks for all your work man

**Comment by Sharcoux** [comment]
Actually, you can also work around this issue by adding a vertical padding to the slider (if it is horizontal).

**Comment by Sharcoux** [comment]
> Wow, thanks for all the info. I'll take a look on those versions you mentioned above. For now I'm going to go ahead and use the community/slider so I can continue working but I'll keep an eye on those issues. Thanks for all your work

By the way, it's not the community slider. It's just callstack slider and the community has nothing to do with it. That's why the support is so poor. ;)

**Comment by maartenvandillen** [comment]
I have the same problem. Was this already fixed? See video for behavior.

https://user-images.githubusercontent.com/6582935/153377252-5d859e42-b166-4eb5-b3d6-da28b5147d77.mp4

**Comment by Sharcoux** [comment]
You can see the progression of this bug in [this issue](https://github.com/facebook/react-native/issues/31843). The issue lies within react-native project. As I'm no Android developer, there isn't much more I can do...

Read my previous messages for more details. If you know Android development better than I do, you could patch React-Native project.

The touch event coordinates seems to be ruled [here](https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/ReactAndroid/src/main/java/com/facebook/react/uimanager/JSTouchDispatcher.java#L81). The coordinates should probably be corrected to rely on the target of the eventListener and not the target of the UI element. I'm not so sure about this, though, as React-Native code is really complex.

**Comment by maartenvandillen** [comment]
Thanks for your response. I will try adding a padding around it.

I switched from this [https://github.com/ptomasroos/react-native-multi-slider](url) package because its vertical orientation did not work at all. However, it does not suffer from this problem. I wonder how they manage that.
 
Although I am also a native Android developer I don't feel comfortable enough to make changes to React Native code.

**Comment by Sharcoux** [comment]
Interesting. They actually rely on the page coordinates instead of the component based referential (which is the part that is broken in Android). That would be quite troublesome to rewrite the code to handle this here. I'd rather wait for Facebook to fix their lib.

**Comment by maartenvandillen** [comment]
Hmm, the button next to my slider is still causing a jump of the value, despite the padding of the slider underneath it.
Hiding the button during sliding solves this, but that is not acceptable.
Is there another work-around? Maybe using setResponder or setResponderCapture?

**Comment by maartenvandillen** [comment]
never mind, I switched to the react-native-elements slider component.

**Comment by Sharcoux** [comment]
Sorry mate. I'm glad you found a solution. I wish someone at Facebook can solve this issue at some point...

**Comment by jonathan-reisdorf** [comment]
For me, adding a `hitSlop` to the slider component helps

**Comment by Sharcoux** [comment]
Nice. I'll add it by default.

**Comment by zewt** [comment]
I think a workaround for this is to use pageX deltas instead of locationX during drags.  Store the initial pageX and locationX during the initial press, and during drags, locationX = initialLocationX + (dragPageX - initialPageX).

**Comment by Sharcoux** [comment]
That's true, but the issue is that you need the pageX/pageY location of the top left corner of the slider itself. The only way to get this is by using "measure". That would require to transform everything into an asynchronous system...

**Comment by Sharcoux** [comment]
I think I solved it. Please try @sharcoux/slider version 7.0.3

Notice the package will slowly move to @react-native-assets/slider as the namespace will be maintained by my company instead of myself, which is safer for everyone. You can update right now or wait for deprecation messages. Feel free to provide feedbacks once tested.

**Comment by zewt** [comment]
> That's true, but the issue is that you need the pageX/pageY location of the top left corner of the slider itself. The only way to get this is by using "measure". That would require to transform everything into an asynchronous system...

The event's page coordinates are only used as deltas against themselves to figure out how far the touch has moved since the initial press, which avoids needing to know the widget's page location.  (That assumes the widget doesn't move along the slider axis while it's being dragged, but if that happens something worse is happening...)

**Comment by Sharcoux** [comment]
Ah, yes, I see. It's true that this should work too. Anyway, the version 7.0.3 should be working too. It's based on touchPageX - containerPageX which is what locationX should be if the implementation was correct on Android. Tell me if it's working as expected in your use case.
