### ISSUE TITLE
Custom track

### ISSUE THREAD

**Issue by MattinNajafi** [Sharcoux/slider#93]
No bug but a question. Is there a way to add trackImage or add a gradient to the track? 

I have a design that im trying to reproduce: 

<img width="315" alt="Skärmavbild 2024-02-08 kl  14 23 17" src="https://github.com/Sharcoux/slider/assets/55448006/7d2c8898-788d-4526-9bc9-7e2feb285e08">

**Comment by Sharcoux** [comment]
Normally, you can try to use `minTrackStyle` and `maxTrackStyle` to do the gradient, but I didn't try.

You can use either a `CustomThumb` or `thumbImage` to do the thumb.

**Comment by MattinNajafi** [comment]
What do you mean by using `minTrackStyle` and `maxTrackStyle`?

As it is today i dont know a way to add gradient to a ViewProp.

**Comment by Sharcoux** [comment]
That might work for web, but as long as it is not natively supported by RN, you'll need to rely on [react-native-linear-gradient](https://www.npmjs.com/package/react-native-linear-gradient). The issue is that this component doesn't use that component to represent the tracks. What you could try is to apply a gradient **over** the track with absolute positioning.

**Comment by Sharcoux** [comment]
You might also try to convince your designer that this gradient will increase the complexity of the project for not so much user benefits, and could be reconsidered.

**Comment by MattinNajafi** [comment]
True!! You can close this.

**Comment by Sharcoux** [comment]
@MattinNajafi CustomTrack is now available in v9.1.0
